pritunl/utils/mail.py
To enable none stmp when no username and password configured for the stmp server.
=> Enable none smtp ssl when missing stmp creds

pritunl/utils/misc.py, requirements.txt
Querying ps binary is not os agnostic. I'm trying to run pritunl under alpine (busybox) for implementing docker container and pritunl fails:
I suggest to use psutil to fix this bug.
=> Using psutil to get process info

pritunl/__main__.py
json.loads is being used to manipulate/validate incoming arguments
it doesn't deal with strings that are not already quoted as json strings
so if it generates an exception try enconding the value with JSONEncoder
we still want to pass in bool/ints directly to json.loads so they become real
json bools/ints
Example error:
```
root@host:~# pritunl set host.sync_address vpn.example.com
Traceback (most recent call last):
File "/usr/bin/pritunl", line 11, in <module>
load_entry_point('pritunl==1.25.1103.21', 'console_scripts', 'pritunl')()
File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/__main__.py", line 154, in main
val = json.loads(val_str)
File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
return _default_decoder.decode(s)
File …
```
=> json.loads usage bug

pritunl/handlers/server.py
Hi, I recently tried setting up Pritunl on a fresh Ubuntu 14.04 vm. I hit a roadblock when trying to add a server - the web interface only said a server error occurred.
Looking into the logs, it turns out that python was throwing an error:
```
File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/handlers/server.py", line 279, in server_put_post
flask.request.json['search_domain'].split(',')])
```
The request data is as such:
```
{
...
replica_count:1,
restrict_routes:true,
search_domain:null,
status:null,
....
}
```
`search_domain` is still a key in the request json, but is `None`. This PR adds a second check to make sure it is not `None` before calling `split` on it.
=> Fix server handler to check if property is None

pritunl/__main__.py
This patch resolves the issue when trying to set a configuration value using the `pritunl set KEY VALUE` command.  Python's opt parse interprets the value as an option to parse and errors with an unknown option error.
```
pritunl set app.sso_saml_cert "-----BEGIN CERTIF.....
age: pritunl [command] [options]
Command Help: pritunl [command] --help
Commands:
start                 Start server
version               Print the version and exit
setup-key             Print the setup key and exit
import pritunl
reset-password        Reset administrator password
reset-version         Reset database version to server version
reset-ssl-cert        Reset the server ssl certificate
reconfigure           Reconfigure database connection
set-mongodb           Set the mongoldb uri
logs …
```
=> Fix issue with pritunl set KEY Value comamnd where VALUE has hyphens

pritunl/utils/aws.py
Somehow, boto is not parsing the xml returned from AWS correctly. I can't seem to identify anything special about the route table that it's messing up. It is of the same form as everything else. The only thing that differentiates it is that it has almost 100 routes. Perhaps the parser boto uses gives up at that point?
I'm unsure. I tried digging into the boto code, but came out completely flummoxed.
I didn't notice my text editor had altered the file until I was writing this PR. If you'd prefer I don't change the style, I can go back and update this PR. Let me know if there's anything you'd like me to add (tests?).
=> Filters out route tables that have None for id

pritunl/utils/aws.py
create_route would only be called whenever new networks/server links are added
for the very first time to a table.
replace_route however would be called any time a vpn service is stopped/started,
a failover occurs, etc
when pritunl encounters the ec2 api limit issue, this issue is compounded as
pritunl bails out, leaving dangling routes that will need to be replaced on next
startup.
by swapping the order we should see a 50% decrease in api calls for existing
services/routes.  the trade off being the first time you add something, 2 calls occur.
=> this swaps the calls to the vpc create_route and replace_route.

pritunl/server/instance.py
When calling server_config() on a plugin, the output is concatenated using a 
newline. Except in this case the newline was `/n` instead of `\n`.
=> Fix OpenVPN configuration plugin hook

pritunl/plugins/plugins.py
Correcting this problem:
Original exception is not shown. Since error occurs elsewhere.
=> Fixed error displaying an exception from user plugin

pritunl/iptables.py
Current sorting method does all ACCEPT rules and then all MASQ rules.  This can
lead to mismatch issues, if you need a subset of a network to have one behavior
while the rest of the network needs the other.
For example, say you need:
* `172.16.1.2/32` to be NAT'd 
* `172.16.1.0/24` to not be NAT'd.  
The current code would lay the rules down as:
```
Chain POSTROUTING (policy ACCEPT)
num  target     prot opt source               destination
1     all  --  172.30.1.0/24        172.16.0.0/24        /* pritunl-583c953f26365b65dbfd2c59 */
2     all  --  172.30.1.0/24        172.16.1.0/24        /* pritunl-583c953f26365b65dbfd2c59 */
3     all  --  172.30.1.0/24        172.31.0.0/16        /* pritunl-583c953f26365b65dbfd2c59 */
4    MASQUERADE  all  --  172.30.1.0/24        172.16.1.2 …
```
=> Improve iptable sorting

pritunl/server/server.py, pritunl/server/utils.py
the `route` variable is a dict, so we need to reference the `network` key else the comparison is always false.
=> route is a dict

tools/add_aws_ranges.py
Adding a conditional for running this script in `python3.x`. When using `python3.x`, the `b64.encode` function requires `bytes` or `bytearray` instead of `str`.
Using the script in `python3.x` without encoding the string yields the following:
```
Traceback (most recent call last):
File "add_aws_ranges.py", line 100, in <module>
data=json.dumps(routes),
File "add_aws_ranges.py", line 48, in auth_request
hashlib.sha256).digest())
File "/Users/jsmith/.pyenv/versions/3.6.3/lib/python3.6/hmac.py", line 144, in new
return HMAC(key, msg, digestmod)
File "/Users/jsmith/.pyenv/versions/3.6.3/lib/python3.6/hmac.py", line 42, in __init__
raise TypeError("key: expected bytes or bytearray, but got %r" % type(key).__name__)
TypeError: key: expected bytes or bytearray, but got 'str'
```
Links:
- …
=> Encode strings with utf-8 if using python3.x

pritunl/user/user.py
We had discussed this on 10 September 2018 and a patch was put through,
and I confirmed it had fixed our issues after it went live, but this
week it occurred to me I had tested my own code and not the patch you'd
put through. As such, full tunnel connections still aren't working
correctly. We realized this after upgrading to the latest Pritunl. This
patch is what is on our Pritunl web host now.
On 13 September 2018, you said:
> I don't think it will work but there isn't a significant use case for
> routing all traffic on Chrome OS so it isn't something that I plan on
> fixing.
You were correct, it didn't work, since the patch (https://github.com/pritunl/pritunl/commit/8e02657fcc1fc407307d5d2a84c19e83f990921b) didn't follow the
instructions Google had given us:
> On client side you need to …
=> Removes IgnoreDefaultRoute from chrome ONC

pritunl/user/user.py
I noticed that the generated profiles have some lines with trailing
whitespace and tracked down this line.
To compare:
```python
>>> import json
>>> json.dumps({'a': 'b', 'c': 'd'}, indent=1)
'{\n "a": "b", \n "c": "d"\n}'
>>> json.dumps({'a': 'b', 'c': 'd'}, indent=1, separators=(',', ': '))
'{\n "a": "b",\n "c": "d"\n}'
>>> import sys
>>> sys.version
'2.7.15 ...'
```
Also note that this is not an issue on Python 3.7.
=> Dropping space in comma separator for `json.dumps`

README.md
Fixed script for debian buster with MongoDB 4.2 from the specified repo (4.0 is not available anymore)
=> Fixed script for debian buster with MongoDB 4.2

pritunl/handlers/subscription.py
...in case the browser still uses the old plan and tries to ask the server for the old styles. This will prevent any exceptions thrown on the server console and just answers the request with a default value...
=> Added advanced error handling at subscription.py

pritunl/constants.py
txqueuelen defaults to 100 on openvpn,   changing it to 1000 has a large performance throughput increase on the clients.   I have been running it with this patched in for several months with no issues. 
here is a reference for more details
https://ivanvari.com/solving-openvpn-poor-throughput-and-packet-loss/
=> add txqueuelen to server config

requirements.txt
After a couple of hours i got a lot of errors, and devices unable to connect to the OpenVPN.
The issue seems to be https://github.com/svinota/pyroute2/issues/704
A fix was merged on the 16th of May, and the first release after that merge was 0.5.13
I updated my servers to 0.5.14 and haven't had an issue since, which by now is about a week.
=> update pyroute2 to 0.5.14

pritunl/acme_tiny.py
The original error:
```
Traceback (most recent call last):
File "/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/task.py", line 82, in run
self.task()
File "/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/tasks/acme_update.py", line 42, in task
acme.update_acme_cert()
File "/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/acme.py", line 68, in update_acme_cert
cert = get_acme_cert(settings.app.acme_key, csr)
File "/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/acme.py", line 43, in get_acme_cert
set_acme,
File "/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/acme_tiny.py", line 124, in get_crt
authorization, _, _ = _do_request(auth_url, err_msg="Error getting challenges")
File "/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/acme_tiny.py", line 44, in …
```
=> Update acme_tiny to support LetsEncrypt Staging

pritunl/sso/duo.py
There would be no resp_data in case of a failure. So this should log the entire data (more here https://help.duo.com/s/article/1338?language=en_US )
=> Fix logging of duo errors

pritunl/iptables.py, pritunl/server/instance.py
https://docs.pritunl.com/discuss/60b440598f2159007e377fa8
There is problem of your outbound interface detection:
If I have 2 interfaces:
```
eth0: 10.0.0.1/24
eth1: 10.0.1.1/24
```
And I configure like this:
It will generate this iptables rule:
```
iptables -t nat -A POSTROUTING -s 192.168.226.0/24 -o eth0 -d 10.0.0.0/8 -m comment --comment pritunl-60b1a13e3de6b2ed5c4d8e5f -j MASQUERADE
```
because it detect ```if network_obj in route_net:``` at pritunl/server/instance.py line 582
https://github.com/KusakabeSi/pritunl/blob/78381ed1c2429116649dd598ddfef6f7fb943308/pritunl/server/instance.py#L582
But eth0 only cover small piece of the network that I need to NAT with, this will cause I can't reach ```10.0.1.0/24``` at all because it's on eth1 instead of eth0
The correct iptables generated …
=> [bug fix] Wrong outbound interface detection.

pritunl/auth/administrator.py
There is a problem of `check_session` function.
When `auth_token` is not none, it will call `utils.const_compare` fucntion to compare `auth_signature` and `auth_test_signature`. The `utils.const_compare` require two str type params. But `auth_test_signature` is a bytes. It will be crash.
So, before call `utils.const_compare`, `auth_test_signature` should be decode.
=> fix check_session crash bug

README.md
Hi,
Here's a small fix for people that build another version than master, since the current cd command won't work properly if using a VERSION value other than "master".
=> README build instructions not valid when using a version other than "master"

pritunl/constants.py, pritunl/handlers/settings.py
Hey there! I've accidentally found this typo when working on `settings_override` resource for [Pritunl Terraform provider](https://github.com/disc/terraform-provider-pritunl).
=> Fixed typo in "auditing" constants

pritunl/setup/mongo.py
Last weekend, acme took tens of minutes to go through for me. This broke
the letsencrypt task flow as the challenge token disappeared from the
table meanwhile.
=> Raise acme challenge expiration from 180s to 3600s

pritunl/settings/app.py, pritunl/sso/azure.py
Currently when setting the `app.sso_azure_mode` to `groups` it will sync all groups from Azure (Security and Distribution groups). This isn’t handled very well on the ui when viewing the users as it will overflow from one row to the others, and getting all the groups synced was not useful for us.
The suggested changes add the ability to select if you want only security groups or all groups (where currently all groups are forced). Usually security groups will be used for access control. In addition to this, it also allows a new list option to filter out which groups to be synced.
So to completely make us of this feature you need to set the following.
```
app.sso_azure_mode = “groups”
app.sso_azure_security_groups_only = true
app.sso_azure_allow_groups = [ “AD_GROUP_NAME_ONE”, …
```
=> Finegrained azure group sync control

pritunl/cache.py
Option ```pritunl app.redis_uri redis://localhost/0``` not work as expected.
The point is that redis cache sends response in bytes.
And such respone does not match in ```runners/listener.py:23```
```
msg['channel'] == b"servers" # but expected "servers"
```
runners/listener.py:
```
....
for msg in messenger.subscribe(list(listener.channels.keys())):
for lstnr in listener.channels[msg['channel']]: # <==== this line
try:
queue.put(lstnr, msg)
size = queue.size()
....
```
=> Decode redis response as string instead of bytes

pritunl/acmetiny.py
Deprecated since python version 3.3 and merged into OSError..
=> Update deprecated IOError

pritunl/journal/__init__.py
Hey Pritunl team,
I'm running Pritunl in a Docker container, following the official docs for [installation](https://docs.pritunl.com/docs/installation), [backup](https://docs.pritunl.com/docs/backup), and [WireGuard](https://docs.pritunl.com/docs/wireguard)—huge thanks for the great documentation!
I’ve successfully sent logs from `/var/log/pritunl.log` to my monitoring platform without any issues. However, when trying to send journal logs in `/var/log/pritunl_journal.log`, I ran into a problem—the timestamps are in UNIX time as a float.
Some monitoring platforms like [Datadog](https://docs.datadoghq.com/service_management/events/pipelines_and_processors/date_remapper/), [Elasticsearch](https://www.elastic.co/guide/en/elasticsearch/reference/current/date.html), and …
=> Change journal timestamp type
